server:
  port: 8080
spring:  datasource:    url: jdbc:mysql://192.168.137.120:3306/flowable01?characterEncoding=UTF-8&nullCatalogMeansCurrent=true&useSSL=false    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot  
    
flowable:
  async-executor-activate: false
  database-schema-update: true      